services:
  db:
    image: mysql:8.0
    container_name: bookstore-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookstore
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    container_name: bookstore-api
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: bookstore
      DB_PORT: 3306
      PORT: 3000
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    working_dir: /app
    command: ['node', 'src/app.js']

volumes:
  mysql_data:
