services:
  db:
    image: mysql:8.0
    container_name: bookstore-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookstore
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  book-service:
    build:
      context: ./book-service
    depends_on:
      - db
    ports:
      - '3001:3000'

  customer-service:
    build:
      context: ./customer-service
    depends_on:
      - db
    ports:
      - '3002:3000'

  bff-web:
    build:
      context: ./bff-web
    depends_on:
      - book-service
      - customer-service
    ports:
      - '3003:80'

  bff-mobile:
    build:
      context: ./bff-mobile
    depends_on:
      - book-service
      - customer-service
    ports:
      - '3004:80'

volumes:
  mysql_data:
