services:
  db:
    image: mysql:8.0
    container_name: bookstore-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adminadmin
      MYSQL_DATABASE: bookstore
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminadmin
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./book-service/book-service.env

  book-service:
    build:
      context: ./book-service
    depends_on:
      - db
    ports:
      - '3001:3000'
    env_file:
      - ./book-service/book-service.env

  customer-service:
    build:
      context: ./customer-service
    depends_on:
      - db
    ports:
      - '3002:3000'
    env_file:
      - ./customer-service/customer-service.env

  bff-web:
    build:
      context: ./bff-web
    depends_on:
      - book-service
      - customer-service
    ports:
      - '3003:80'
    env_file:
      - ./bff-web/web.env

  bff-mobile:
    build:
      context: ./bff-mobile
    depends_on:
      - book-service
      - customer-service
    ports:
      - '3004:80'
    env_file:
      - ./bff-mobile/mobile.env

volumes:
  mysql_data:
